version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - 1.16.0-RC1
    - 1.16.0-RC2
    - 1.16.0-RC3
